/**
 * AUTHOR - PUNIT MORE
 * DATE - 09-01-2024;
 * DESC - SPOOLMAN-ERMAN --> 9DOT-->PROJECT-->PRODUCTION-->FITUP COMPLETION POM REPOSITORY
 * UPDATED - 
 */


package com.pcpl.spoolman.production;

import java.util.List;

import org.apache.poi.hssf.record.UserSViewBegin;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public class TestSpool_FitupCompletion {

	WebDriver driver ;
	
	public TestSpool_FitupCompletion(WebDriver driver) {
		
		this.driver = driver;
		PageFactory.initElements(driver,this);
		
	}
	
	@FindBy (xpath = "//input[@aria-owns=\"ContractorID_listbox\"]")
	private WebElement SubContractor_DDTXT;
	
	@FindBy (xpath = "(//i[@class=\"fas fa-edit\"])[1]/..")
	private WebElement SelectionWindowEdit_BTN;
	
	@FindBy (xpath = "(//i[@class=\"fas fa-edit\"])[2]/..")
	private WebElement CreationWindowEdit_BTN;
	
	@FindBy (xpath = "//span[@class=\"fa fa-filter\"]/..")
	private WebElement SelectionFilter_BTN;
	
	@FindBy (xpath = "(//span[@class=\"fa fa-columns\"]/..)[1]")
	private WebElement SelectionColumnSetting_BTN;
	
	@FindBy (xpath = "(//span[@class=\"fa fa-columns\"]/..)[2]")
	private WebElement CreationColumnSetting_BTN;
	
	@FindBy (xpath = "(//span[@class=\"fa fa-expand\"]/..)[1]")
	private WebElement SelectionFullscrean_BTN;
	
	@FindBy (xpath = "(//span[@class=\"fa fa-expand\"]/..)[2]")
	private WebElement CreationFullscrean_BTN;
	
	@FindBy (xpath = "//span[@class=\"fa fa-compress\"]")
	private WebElement FitupCompletionCompress_BTN;
	
	@FindBy (xpath = "//span[@class=\"fa fa-file-alt\"]/..")
	private WebElement ReportDetails_BTN;
	
	@FindBy (xpath = "//span[@class=\"fa fa-save\"]/..")
	private WebElement CreationSave_BTN;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGrid\"]/div[3]/table/tbody/tr/td[3]")
	private List<WebElement> Selection_SpoolNameList;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGrid\"]/div[3]/table/tbody/tr/td[4]")
	private List<WebElement> Selection_JointNoList;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGridMore\"]/div[3]/table/tbody/tr/td[2]")
	private List<WebElement> Creation_SpoolNameList;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGridMore\"]/div[3]/table/tbody/tr/td[3]")
	private List<WebElement> Creation_JointNoList;
	
//	@FindBy (xpath = "(//div[@id='CreateViewGrid']//div)[5]//div[1]//table//th | "
//			+ "(//div[@id='CreateViewGrid']//div)[5]//div[2]//table//th[not(contains(@style, 'display:none'))]")
//	private List<WebElement> SelectionWindowHeaders_List;
	
	@FindBy (xpath = "(//div[@id='CreateViewGrid']//div)[5]//div[1]//table//th[not(contains(@class,"
			+ " 'Nocolumnmenu checkAllme k-header k-with-icon'))] | (//div[@id='CreateViewGrid']//div)[5]"
			+ "//div[2]//table//th[not(contains(@style, 'display:none'))]")
	private List<WebElement> SelectionWindowHeaders_List;
	
	@FindBy (xpath = "(//div[@id=\"CreateViewGridMore\"]//div)[5]//table//th | (//div[@id=\"CreateViewGridMore\"]"
			+ "//div)[4]//table//th[not(contains(@style, 'display:none'))]")
	private List<WebElement> CreationWindowHeaders_List;
	
	//FITUP REPORT SELECTION...
	
	@FindBy (xpath = "//input[@id=\"drpJobCard\"]/..//span//input")
	private WebElement FRSelectionJobCard_DDTXT;
	
	@FindBy (xpath = "(//div[@id=\"drpJobCard-list\"])[1]//ul[@id=\"drpJobCard_listbox\"]//li")
	private List<WebElement> FRSelectionJobCard_DDList;
	
	@FindBy (xpath = "//input[@id=\"drpView\"]/..//span//input")
	private WebElement FRSelectionView_DDTXT;
	
	@FindBy (xpath = "(//div[@id=\"drpView-list\"])[1]//ul[@id=\"drpView_listbox\"]//li")
	private List<WebElement> FRSelectionView_DDList;
	
	@FindBy (id = "WVIJointHidechk")
	private WebElement FRSelectionJointHide_Checkbox;
	
	@FindBy (id = "Search")
	private WebElement FRSelectionSearch_BTN;
	
	@FindBy (id = "Cleared")
	private WebElement FRSelectionCleared_BTN;
	
	@FindBy (xpath = "//div[@id=\"OverlayModalOpen\"]//i[@class=\"k-i-close k-icon\"]")
	private WebElement FRSelectionClose_BTN;
	
	@FindBy (id = "viewfilter")
	private WebElement AppliedFiltersText;
	
//	FITUP REPORT CREATION...
	
	@FindBy (id = "ChkReportNo")
	private WebElement AutogenerateReportNo_CHECKBOX;
	
	@FindBy (xpath = "(//input[@id=\"ReportNoDropdown\"]/..//span//span)[1]")
	private WebElement ReportNo_AutoGenerated;
	
	@FindBy (xpath = "//span[@aria-owns=\"ReportNoDropdown_listbox\"]")
	private WebElement ReportNo_DD;
	
	@FindBy (xpath = "//*[@id=\"MRListModal\"]/div[1]/div/i")
	private WebElement FitupReportCreationClose_BTN;
	
	@FindBy (xpath = "//label[text()=\"Apply All Observation :\"]/../span/span/input")
	private WebElement ApplyAllObservation_DDTXT;
	
	@FindBy (id = "btnSave")
	private WebElement FitupReportCreationSave_BTN;
	
	@FindBy (id = "ToptotalRecords")
	private WebElement TotalRecordsSelection;
	
	@FindBy (id = "BottomtotalRecords")
	private WebElement TotalRecordsCreations;
	
	@FindBy (xpath = "//input[@aria-label=\"Select all rows\"]")
	private WebElement SelectionSelectAllRow_CHECKBOX;
	
	@FindBy (xpath = "//input[@aria-owns=\"ReportNoDropdown_listbox\"]")
	private WebElement ReportNoDDInput;
	
	@FindBy (xpath = "//button[text()=\"Add\"]")
	private WebElement ReportNoADD_BTN;
		
	@FindBy (xpath = "(//input[@aria-label=\"Select row\"])[1]")
	private WebElement select1stRow_CHECKBOX;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGridMore\"]  //th[contains(@data-field,\"Thickness\")]")
	private WebElement CreationThickness_Col;
	
	@FindBy (xpath = "(//div[@id=\"CreateViewGridMore\"]  //td[contains(@data-field,\"Thickness\")])[1]")
	private WebElement CreationThickness_1stRow;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGridMore\"]  //th[contains(@data-field,\"WeldLength\")]")
	private WebElement CreationWeldLength_Col;
	
	@FindBy (xpath = "(//div[@id=\"CreateViewGridMore\"]//td[contains(@data-field,\"WeldLength\")])[1]")
	private WebElement CreationWeldLength_1stRow;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGridMore\"]  //tH[contains(@data-field,\"Part1ComponentType\")]")
	private WebElement  CreationPart_1ItemType_Col;
	
	@FindBy (id = "Thickness")
	private WebElement CreationThickness_Input;
	
	@FindBy (id =  "WeldLength")
	private WebElement CreationWeldLength_Input;

//	FITUP COMPLETION SIDEBAR
	
	@FindBy (id = "FitupCompletion")
	private WebElement SideBarFitupCompletion;
	
	@FindBy (id = "FitupViewModifyReport")
	private WebElement SideBarFitupViewModifyReport;
	
	@FindBy (xpath = "//span[text()=\"Fitup Report\"]/..")
	private WebElement SideBarFitupReport;
	
	@FindBy (xpath = "//span[text()=\"Data Saved Successfully!\"]")
	private WebElement DataSavedSuccessfully_POPUP;
	
	@FindBy (xpath = "//span[text()=\"Data Saved Successfully!\"]/../button")
	private WebElement DataSavedSuccessfully_POPUPClose;
	
	@FindBy (xpath = "//span[text()=\"Save Data Successfully\"]")
	private WebElement PMIDataSavedSuccessfully_POPUP;
	
	@FindBy (xpath = "//span[text()=\"Save Data Successfully\"]/../button")
	private WebElement PMIDataSavedSuccessfully_POPUPClose;
	
	@FindBy (xpath = "(//th[text()=\"Spool Name\"]//span)[1]")
	private WebElement SpoolName3Dots;
	
	@FindBy (xpath = "// div[@id=\"CreateViewGrid\"] // th[contains(text(),\"Joint No.\")]//span")
	private WebElement JointNo3DOTS;
	
	@FindBy (xpath = "//div[@id=\"CreateViewGrid\"]/div[3]/table/tbody/tr[1]/td[3]")
	private WebElement SpoolNameFR;
	
	@FindBy (xpath = "//button[@class=\"bootbox-close-button close\"]")
	private WebElement RportNoIsNotFilledPopup_Close;
	
	@FindBy (xpath = "//button[text()=\"Yes\"]")
	private WebElement RportNoIsNotFilledPopup_Yes;
	
	@FindBy (xpath = "//button[text()=\"No\"]")
	private WebElement RportNoIsNotFilledPopup_No;
	
	
	

//	FILL MASTER
	
	@FindBy (id = "filterProgress")
	private WebElement FillMasterDetailsCollapse;
	
	@FindBy (xpath = "//span[@aria-owns=\"YardId_listbox\"]")
	private WebElement FM_YardDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"YardId_listbox\"]")
	private WebElement FM_YardDDInput;
	
//	@FindBy (xpath = "//div[@id=\"YardId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"YardId-list\"]//div)[4]//button")
	private WebElement FM_YardAddNewItem;
	
	@FindBy (xpath = "//span[@aria-owns=\"ModuleNoId_listbox\"]")
	private WebElement FM_ModuleNoDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"ModuleNoId_listbox\"]")
	private WebElement FM_ModuleNoDDInput;
	
//	@FindBy (xpath = "//div[@id=\"ModuleNoId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"ModuleNoId-list\"]//div)[4]//button")
	private WebElement FM_ModuleNoAddNewItem;
	
	@FindBy (xpath = "//span[@aria-owns=\"RFINoId_listbox\"]")
	private WebElement FM_RFINoDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"RFINoId_listbox\"]")
	private WebElement FM_RFINoDDInput;
	
//	@FindBy (xpath = "//div[@id=\"RFINoId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"RFINoId-list\"]//div)[4]//button")
	private WebElement FM_RFINoAddNewItem;
	
	@FindBy (id = "DateRFI")
	private WebElement FM_DateOfRFI;
	
	@FindBy (xpath = "//span[@aria-owns=\"LocationId_listbox\"]")
	private WebElement FM_LocationDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"LocationId_listbox\"]")
	private WebElement FM_LocationDDInput;
	
//	@FindBy (xpath = "//div[@id=\"LocationId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"LocationId-list\"]//div)[4]//button")
	private WebElement FM_LocationAddNewItem;
	
	@FindBy (id = "InspectionDate")
	private WebElement FM_InspectionDate;
	
	@FindBy (xpath = "//span[@aria-owns=\"CodeSpecId_listbox\"]")
	private WebElement FM_CodeSpecDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"CodeSpecId_listbox\"]")
	private WebElement FM_CodeSpecDDInput;
	
//	@FindBy (xpath = "//div[@id=\"CodeSpecId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"CodeSpecId-list\"]//div)[4]//button")
	private WebElement FM_CodeSpecAddNewItem;
	
	@FindBy (xpath = "//span[@aria-owns=\"ProcedureId_listbox\"]")
	private WebElement FM_ProcedureDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"ProcedureId_listbox\"]")
	private WebElement FM_ProcedureDDInput;
	
//	@FindBy (xpath = "//div[@id=\"ProcedureId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"ProcedureId-list\"]//div)[4]//button")
	private WebElement FM_ProcedureAddNewItem;
	
	@FindBy (xpath = "//span[@aria-owns=\"AcceptCriteriaId_listbox\"]")
	private WebElement FM_AcceptCriteriaDD;
	
	@FindBy (xpath = "//input[@aria-owns=\"AcceptCriteriaId_listbox\"]")
	private WebElement FM_AcceptCriteriaDDInput;
	
//	@FindBy (xpath = "//div[@id=\"AcceptCriteriaId-list\"]//div[4]//button")
	@FindBy (xpath = "(//div[@id=\"AcceptCriteriaId-list\"]//div)[4]//button")
	private WebElement FM_AcceptCriteriaAddNewItem;
	
	
	
	@FindBy (xpath = "//div[text()=\"Do you want to upload signature ?\"]/../..")
	private WebElement SignaturePOPUP;
	
	@FindBy (xpath = "//div[text()=\"Do you want to upload signature ?\"]/..//button")
	private WebElement SignaturePOPUPClose;
	
	@FindBy (xpath = "//button[text()=\"Yes\"]")
	private WebElement SignaturePOPUPYes;
	
	@FindBy (xpath = "//button[text()=\"No\"]")
	private WebElement SignaturePOPUPNo;
	
	
//	FILTER
	
	@FindBy (xpath = "//span[text()=\"Filter\"]")
	private WebElement FunnelFilter;
	
	@FindBy (xpath = "//input[@title=\"Value\"]")
	private WebElement FilterValue;
	
	@FindBy (xpath = "(//button[text()=\"Filter\"])")
	private WebElement FFFilter_BTN;
	
	@FindBy (xpath = "//button[text()=\"Clear\"]")
	private WebElement FFClear_BTN;

//	wait
	
	@FindBy (id = "pleaseWaitModal")
	private WebElement fcPleaseWaitModal;
	
	
	
	
	/**
	 * @return the driver
	 */
	public WebDriver getDriver() {
		return driver;
	}

	/**
	 * @return the subContractor_DDTXT
	 */
	public WebElement getSubContractor_DDTXT() {
		return SubContractor_DDTXT;
	}

	/**
	 * @return the selectionWindowEdit_BTN
	 */
	public WebElement getSelectionWindowEdit_BTN() {
		return SelectionWindowEdit_BTN;
	}

	/**
	 * @return the creationWindowEdit_BTN
	 */
	public WebElement getCreationWindowEdit_BTN() {
		return CreationWindowEdit_BTN;
	}

	/**
	 * @return the filter_BTN
	 */
	public WebElement getSelectionFilter_BTN() {
		return SelectionFilter_BTN;
	}

	/**
	 * @return the selectionColumnSetting_BTN
	 */
	public WebElement getSelectionColumnSetting_BTN() {
		return SelectionColumnSetting_BTN;
	}

	/**
	 * @return the creationColumnSetting_BTN
	 */
	public WebElement getCreationColumnSetting_BTN() {
		return CreationColumnSetting_BTN;
	}

	/**
	 * @return the selectionFullscrean_BTN
	 */
	public WebElement getSelectionFullscrean_BTN() {
		return SelectionFullscrean_BTN;
	}

	/**
	 * @return the creationFullscrean_BTN
	 */
	public WebElement getCreationFullscrean_BTN() {
		return CreationFullscrean_BTN;
	}

	/**
	 * @return the reportDetails_BTN
	 */
	public WebElement getReportDetails_BTN() {
		return ReportDetails_BTN;
	}

	/**
	 * @return the creationSave_BTN
	 */
	public WebElement getCreationSave_BTN() {
		return CreationSave_BTN;
	}

	/**
	 * @return the fRSelectionJobCard_DDTXT
	 */
	public WebElement getFRSelectionJobCard_DDTXT() {
		return FRSelectionJobCard_DDTXT;
	}

	/**
	 * @return the fRSelectionJobCard_DDList
	 */
	public List<WebElement> getFRSelectionJobCard_DDList() {
		return FRSelectionJobCard_DDList;
	}

	/**
	 * @return the fRSelectionView_DDTXT
	 */
	public WebElement getFRSelectionView_DDTXT() {
		return FRSelectionView_DDTXT;
	}

	/**
	 * @return the fRSelectionView_DDList
	 */
	public List<WebElement> getFRSelectionView_DDList() {
		return FRSelectionView_DDList;
	}

	/**
	 * @return the fRSelectionJointHide_Checkbox
	 */
	public WebElement getFRSelectionJointHide_Checkbox() {
		return FRSelectionJointHide_Checkbox;
	}

	/**
	 * @return the fRSelectionSearch_BTN
	 */
	public WebElement getFRSelectionSearch_BTN() {
		return FRSelectionSearch_BTN;
	}

	/**
	 * @return the fRSelectionCleared_BTN
	 */
	public WebElement getFRSelectionCleared_BTN() {
		return FRSelectionCleared_BTN;
	}

	/**
	 * @return the fRSelectionClose_BTN
	 */
	public WebElement getFRSelectionClose_BTN() {
		return FRSelectionClose_BTN;
	}

	/**
	 * @return the appliedFiltersText
	 */
	public WebElement getAppliedFiltersText() {
		return AppliedFiltersText;
	}

	/**
	 * @return the autogenerateReportNo_CHECKBOX
	 */
	public WebElement getAutogenerateReportNo_CHECKBOX() {
		return AutogenerateReportNo_CHECKBOX;
	}

	/**
	 * @return the reportNo_AutoGenerated
	 */
	public WebElement getReportNo_AutoGenerated() {
		return ReportNo_AutoGenerated;
	}

	/**
	 * @return the reportNo_DD
	 */
	public WebElement getReportNo_DD() {
		return ReportNo_DD;
	}

	/**
	 * @return the fitupReportCreationClose_BTN
	 */
	public WebElement getFitupReportCreationClose_BTN() {
		return FitupReportCreationClose_BTN;
	}

	/**
	 * @return the applyAllObservation_DDTXT
	 */
	public WebElement getApplyAllObservation_DDTXT() {
		return ApplyAllObservation_DDTXT;
	}

	/**
	 * @return the fitupReportCreationSave_BTN
	 */
	public WebElement getFitupReportCreationSave_BTN() {
		return FitupReportCreationSave_BTN;
	}

	/**
	 * @return the totalRecordsSelection
	 */
	public WebElement getTotalRecordsSelection() {
		return TotalRecordsSelection;
	}

	/**
	 * @return the totalRecordsCreations
	 */
	public WebElement getTotalRecordsCreations() {
		return TotalRecordsCreations;
	}

	/**
	 * @return the selectAllRow_CHECKBOX
	 */
	public WebElement getSelectAllRow_CHECKBOX() {
		return SelectionSelectAllRow_CHECKBOX;
	}

	/**
	 * @return the select1stRow_CHECKBOX
	 */
	public WebElement getSelect1stRow_CHECKBOX() {
		return select1stRow_CHECKBOX;
	}

	/**
	 * @return the reportNoDDInput
	 */
	public WebElement getReportNoDDInput() {
		return ReportNoDDInput;
	}

	/**
	 * @return the reportNoADD_BTN
	 */
	public WebElement getReportNoADD_BTN() {
		return ReportNoADD_BTN;
	}

	/**
	 * @return the fitupCompletionCompress_BTN
	 */
	public WebElement getFitupCompletionCompress_BTN() {
		return FitupCompletionCompress_BTN;
	}

	/**
	 * @return the creationThickness_Col
	 */
	public WebElement getCreationThickness_Col() {
		return CreationThickness_Col;
	}

	/**
	 * @return the creationThickness_1stRow
	 */
	public WebElement getCreationThickness_1stRow() {
		return CreationThickness_1stRow;
	}

	/**
	 * @return the creationWeldLength_Col
	 */
	public WebElement getCreationWeldLength_Col() {
		return CreationWeldLength_Col;
	}

	/**
	 * @return the creationWeldLength_1stRow
	 */
	public WebElement getCreationWeldLength_1stRow() {
		return CreationWeldLength_1stRow;
	}

	/**
	 * @return the creationPart_1ItemType_Col
	 */
	public WebElement getCreationPart_1ItemType_Col() {
		return CreationPart_1ItemType_Col;
	}

	/**
	 * @return the creationThickness_Input
	 */
	public WebElement getCreationThickness_Input() {
		return CreationThickness_Input;
	}

	/**
	 * @return the creationWeldLength_Input
	 */
	public WebElement getCreationWeldLength_Input() {
		return CreationWeldLength_Input;
	}

	/**
	 * @return the sideBarFitupCompletion
	 */
	public WebElement getSideBarFitupCompletion() {
		return SideBarFitupCompletion;
	}

	/**
	 * @return the sideBarFitupViewModifyReport
	 */
	public WebElement getSideBarFitupViewModifyReport() {
		return SideBarFitupViewModifyReport;
	}

	/**
	 * @return the sideBarFitupReport
	 */
	public WebElement getSideBarFitupReport() {
		return SideBarFitupReport;
	}

	/**
	 * @return the selectionSelectAllRow_CHECKBOX
	 */
	public WebElement getSelectionSelectAllRow_CHECKBOX() {
		return SelectionSelectAllRow_CHECKBOX;
	}

	/**
	 * @return the dataSavedSuccessfully_POPUP
	 */
	public WebElement getDataSavedSuccessfully_POPUP() {
		return DataSavedSuccessfully_POPUP;
	}

	/**
	 * @return the dataSavedSuccessfully_POPUPClose
	 */
	public WebElement getDataSavedSuccessfully_POPUPClose() {
		return DataSavedSuccessfully_POPUPClose;
	}

	/**
	 * @return the pMIDataSavedSuccessfully_POPUP
	 */
	public WebElement getPMIDataSavedSuccessfully_POPUP() {
		return PMIDataSavedSuccessfully_POPUP;
	}

	/**
	 * @return the pMIDataSavedSuccessfully_POPUPClose
	 */
	public WebElement getPMIDataSavedSuccessfully_POPUPClose() {
		return PMIDataSavedSuccessfully_POPUPClose;
	}

	/**
	 * @return the spoolName3Dots
	 */
	public WebElement getSpoolName3Dots() {
		return SpoolName3Dots;
	}

	/**
	 * @return the jointNo3DOTS
	 */
	public WebElement getJointNo3DOTS() {
		return JointNo3DOTS;
	}

	/**
	 * @return the spoolNameFR
	 */
	public WebElement getSpoolNameFR() {
		return SpoolNameFR;
	}

	
	
	/**
	 * @return the rportNoIsNotFilledPopup_Close
	 */
	public WebElement getRportNoIsNotFilledPopup_Close() {
		return RportNoIsNotFilledPopup_Close;
	}

	/**
	 * @return the rportNoIsNotFilledPopup_Yes
	 */
	public WebElement getRportNoIsNotFilledPopup_Yes() {
		return RportNoIsNotFilledPopup_Yes;
	}

	/**
	 * @return the rportNoIsNotFilledPopup_No
	 */
	public WebElement getRportNoIsNotFilledPopup_No() {
		return RportNoIsNotFilledPopup_No;
	}

	/**
	 * @return the fillMasterDetailsCollapse
	 */
	public WebElement getFillMasterDetailsCollapse() {
		return FillMasterDetailsCollapse;
	}

	/**
	 * @return the fM_YardDD
	 */
	public WebElement getFM_YardDD() {
		return FM_YardDD;
	}

	/**
	 * @return the fM_YardDDInput
	 */
	public WebElement getFM_YardDDInput() {
		return FM_YardDDInput;
	}

	/**
	 * @return the fM_YardAddNewItem
	 */
	public WebElement getFM_YardAddNewItem() {
		return FM_YardAddNewItem;
	}

	/**
	 * @return the fM_ModuleNoDD
	 */
	public WebElement getFM_ModuleNoDD() {
		return FM_ModuleNoDD;
	}

	/**
	 * @return the fM_ModuleNoDDInput
	 */
	public WebElement getFM_ModuleNoDDInput() {
		return FM_ModuleNoDDInput;
	}

	/**
	 * @return the fM_ModuleNoAddNewItem
	 */
	public WebElement getFM_ModuleNoAddNewItem() {
		return FM_ModuleNoAddNewItem;
	}

	/**
	 * @return the fM_RFINoDD
	 */
	public WebElement getFM_RFINoDD() {
		return FM_RFINoDD;
	}

	/**
	 * @return the fM_RFINoDDInput
	 */
	public WebElement getFM_RFINoDDInput() {
		return FM_RFINoDDInput;
	}

	/**
	 * @return the fM_RFINoAddNewItem
	 */
	public WebElement getFM_RFINoAddNewItem() {
		return FM_RFINoAddNewItem;
	}

	/**
	 * @return the fM_DateOfRFI
	 */
	public WebElement getFM_DateOfRFI() {
		return FM_DateOfRFI;
	}

	/**
	 * @return the fM_LocationDD
	 */
	public WebElement getFM_LocationDD() {
		return FM_LocationDD;
	}

	/**
	 * @return the fM_LocationDDInput
	 */
	public WebElement getFM_LocationDDInput() {
		return FM_LocationDDInput;
	}

	/**
	 * @return the fM_LocationAddNewItem
	 */
	public WebElement getFM_LocationAddNewItem() {
		return FM_LocationAddNewItem;
	}

	/**
	 * @return the fM_InspectionDate
	 */
	public WebElement getFM_InspectionDate() {
		return FM_InspectionDate;
	}

	/**
	 * @return the fM_CodeSpecDD
	 */
	public WebElement getFM_CodeSpecDD() {
		return FM_CodeSpecDD;
	}

	/**
	 * @return the fM_CodeSpecDDInput
	 */
	public WebElement getFM_CodeSpecDDInput() {
		return FM_CodeSpecDDInput;
	}

	/**
	 * @return the fM_CodeSpecAddNewItem
	 */
	public WebElement getFM_CodeSpecAddNewItem() {
		return FM_CodeSpecAddNewItem;
	}

	/**
	 * @return the fM_ProcedureDD
	 */
	public WebElement getFM_ProcedureDD() {
		return FM_ProcedureDD;
	}

	/**
	 * @return the fM_ProcedureDDInput
	 */
	public WebElement getFM_ProcedureDDInput() {
		return FM_ProcedureDDInput;
	}

	/**
	 * @return the fM_ProcedureAddNewItem
	 */
	public WebElement getFM_ProcedureAddNewItem() {
		return FM_ProcedureAddNewItem;
	}

	/**
	 * @return the fM_AcceptCriteriaDD
	 */
	public WebElement getFM_AcceptCriteriaDD() {
		return FM_AcceptCriteriaDD;
	}

	/**
	 * @return the fM_AcceptCriteriaDDInput
	 */
	public WebElement getFM_AcceptCriteriaDDInput() {
		return FM_AcceptCriteriaDDInput;
	}

	/**
	 * @return the fM_AcceptCriteriaAddNewItem
	 */
	public WebElement getFM_AcceptCriteriaAddNewItem() {
		return FM_AcceptCriteriaAddNewItem;
	}

	/**
	 * @return the signaturePOPUP
	 */
	public WebElement getSignaturePOPUP() {
		return SignaturePOPUP;
	}

	/**
	 * @return the signaturePOPUPClose
	 */
	public WebElement getSignaturePOPUPClose() {
		return SignaturePOPUPClose;
	}

	/**
	 * @return the signaturePOPUPYes
	 */
	public WebElement getSignaturePOPUPYes() {
		return SignaturePOPUPYes;
	}

	/**
	 * @return the signaturePOPUPNo
	 */
	public WebElement getSignaturePOPUPNo() {
		return SignaturePOPUPNo;
	}

	/**
	 * @return the funnelFilter
	 */
	public WebElement getFunnelFilter() {
		return FunnelFilter;
	}

	/**
	 * @return the filterValue
	 */
	public WebElement getFilterValue() {
		return FilterValue;
	}

	/**
	 * @return the fFFilter_BTN
	 */
	public WebElement getFFFilter_BTN() {
		return FFFilter_BTN;
	}

	/**
	 * @return the fFClear_BTN
	 */
	public WebElement getFFClear_BTN() {
		return FFClear_BTN;
	}

	/**
	 * @return the fcPleaseWaitModal
	 */
	public WebElement getFcPleaseWaitModal() {
		return fcPleaseWaitModal;
	}

	/**
	 * @return the selection_SpoolNameList
	 */
	public List<WebElement> getSelection_SpoolNameList() {
		return Selection_SpoolNameList;
	}

	/**
	 * @return the selection_JointNoList
	 */
	public List<WebElement> getSelection_JointNoList() {
		return Selection_JointNoList;
	}

	/**
	 * @return the creation_SpoolNameList
	 */
	public List<WebElement> getCreation_SpoolNameList() {
		return Creation_SpoolNameList;
	}

	/**
	 * @return the creation_JointNoList
	 */
	public List<WebElement> getCreation_JointNoList() {
		return Creation_JointNoList;
	}

	/**
	 * @return the selectionWindowHeaders_List
	 */
	public List<WebElement> getSelectionWindowHeaders_List() {
		return SelectionWindowHeaders_List;
	}

	/**
	 * @return the creationWindowHeaders_List
	 */
	public List<WebElement> getCreationWindowHeaders_List() {
		return CreationWindowHeaders_List;
	}


	
}
